Add new fields to Location model
fs-masterclasses/masterclasses pull request #13
Opened 2020-08-28 10:50 UTC by mforner13

This PR is the first of two which will replace the fields in the Location table due to the following design changes:
- A masterclass will take place either remotely or in person
- Physical locations will be fetched from the google places API, rather than input manually

I have included the boolean `is_remote` because remote and in person masterclasses will be displayed differently in the app.

**To do**
- Update templates to display Location data from new fields
- Create another migration to remove the old fields

2020-09-01 16:07 UTC, jonodrew commented on app/models.py
> +    remote_joining_instructions = db.Column(db.String, index=True)
Not sure this belongs here

2020-09-01 16:09 UTC, jonodrew requested changes

2020-09-01 16:09 UTC, jonodrew commented on app/models.py
> +    remote_joining_instructions = db.Column(db.String, index=True)
If we want locations to be re-useable maybe move this to the actual Masterclass? As it'll be unique data associated with each Masterclass

2020-09-07 11:38 UTC, mforner13 commented
@jonodrew I have updated the model changes as we discussed last week

2020-09-10 07:17 UTC, jonodrew approved these changes
Looks good to me :+1:

2020-09-14 08:55 UTC, merged